[package]
name = "samplerust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.0"
ringbuf = "0.3"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
